# Включение/отключение интеграции с MythicMobs
mythicmobs-enable: true

# Настройки для интеграции с MythicMobs
mythicmobs:
  # Время (в секундах), в течение которого засчитываются убийства MythicMobs для всех игроков.
  # Это значение будет использоваться по умолчанию для всех мобов, если для них не указано особое время.
  default-credit-time: 10

  # Время (в секундах), в течение которого засчитываются убийства для конкретных типов MythicMobs.
  credit-times:
    ZombieBoss: 30
    SkeletonWarrior: 15
    # Если указано значение 0, убийство засчитывается только тому игроку, который добил моба.
    CommonZombie: 0